### ISSUE TITLE
Repository contains AssistantSeika.

### ISSUE THREAD

**Issue by k896951** [luckiluck/My-Public-Projects#1]
Hello.
I am the creator and rights holder of AssistantSeika.

Your repository contains AssistantSeika, but I have not given you permission for secondary distribution.
I would like you to remove it from your repository as soon as possible.

**Comment by luckiluck** [comment]
Hello.

I'm deeply sorry for uploading your software to my repository without your permission.
I've already removed AssistantSeika from my repository.
